FROM node:20-alpine AS builder

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./

ARG VITE_PLATFORM_URL
ENV VITE_PLATFORM_URL=${VITE_PLATFORM_URL}

RUN npm run build

FROM nginx:alpine AS runner

ENV PORT=80

COPY frontend/default.conf.template /etc/nginx/templates/default.conf.template
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
