import { InterventionType } from './intervention.types.js';

export const CAUSE_INTERVENTION_MAP: Record<string, InterventionType[]> = {
  INSUFFICIENT_FUNDS: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  CREDIT_LIMIT_EXCEEDED: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  MANUAL_3DS_OTP_ABANDONMENT: [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  '3DS_OTP_ABANDONMENT': [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  PAYMENT_VERIFICATION_FAILED: [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  ACQUIRER_PAYMENT_GATEWAY_TIMEOUT: [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  GATEWAY_TIMEOUT: [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  ISSUING_BANK_OUTAGE: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL',
    'RETRY_PAYMENT'
  ],

  ISSUER_TECHNICAL_FAILURE: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL',
    'RETRY_PAYMENT'
  ],

  TECHNICAL_FAILURE: [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL',
    'HUMAN_REVIEW'
  ],

  MERCHANT_TECHNICAL_FAILURE: [
    'RETRY_PAYMENT',
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  PAYMENT_INSTRUMENT_EXPIRED_INVALID: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  PAYMENT_INSTRUMENT_INVALID: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  EXPIRED_CARD: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL'
  ],

  UNKNOWN: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_EMAIL'
  ],

  TRANSACTION_LIMIT_EXCEEDED: [
    'SEND_PAYMENT_LINK',
    'CHANGE_PAYMENT_METHOD_PROMPT',
    'SEND_WHATSAPP',
    'SEND_SMS',
    'SEND_EMAIL',
    'HUMAN_REVIEW'
  ]
};
