import { InterventionDefinition, InterventionType } from './intervention.types.js';

export const INTERVENTION_DEFINITIONS: Record<InterventionType, InterventionDefinition> = {
  RETRY_PAYMENT: {
    type: 'RETRY_PAYMENT',
    name: 'Direct Payment Retry',
    description: 'Re-trigger payment processing attempt using original parameters',
    supportedCauses: [
      'MANUAL_3DS_OTP_ABANDONMENT',
      '3DS_OTP_ABANDONMENT',
      'ACQUIRER_PAYMENT_GATEWAY_TIMEOUT',
      'GATEWAY_TIMEOUT',
      'ISSUING_BANK_OUTAGE',
      'ISSUER_TECHNICAL_FAILURE',
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE'
    ],
    priority: 'HIGH',
    estimatedCost: 0,
    expectedRecoveryProbability: 0.55,
    maxAttempts: 3,
    cooldownSeconds: 300,
    requiredCustomerData: ['paymentAttemptId'],
    requiredMerchantConfig: [],
    supportedChannels: ['API'],
    requiresPaymentLink: false,
    requiresHumanApproval: false,
    requiresResolutionCheck: true,
    terminal: false,
    enabled: true,
    version: 'v1'
  },

  SEND_PAYMENT_LINK: {
    type: 'SEND_PAYMENT_LINK',
    name: 'Send Payment Recovery Link',
    description: 'Generate and send a secure direct payment link to the customer',
    supportedCauses: [
      'INSUFFICIENT_FUNDS',
      'CREDIT_LIMIT_EXCEEDED',
      'MANUAL_3DS_OTP_ABANDONMENT',
      '3DS_OTP_ABANDONMENT',
      'ACQUIRER_PAYMENT_GATEWAY_TIMEOUT',
      'GATEWAY_TIMEOUT',
      'ISSUING_BANK_OUTAGE',
      'ISSUER_TECHNICAL_FAILURE',
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE',
      'PAYMENT_INSTRUMENT_EXPIRED_INVALID',
      'PAYMENT_INSTRUMENT_INVALID',
      'EXPIRED_CARD',
      'INVALID_CARD',
      'INVALID_CVV',
      'TRANSACTION_LIMIT_EXCEEDED'
    ],
    priority: 'HIGH',
    estimatedCost: 0.5,
    expectedRecoveryProbability: 0.70,
    maxAttempts: 2,
    cooldownSeconds: 60,
    requiredCustomerData: ['customerIdentity'],
    requiredMerchantConfig: [],
    supportedChannels: ['EMAIL', 'SMS', 'WHATSAPP'],
    requiresPaymentLink: true,
    requiresHumanApproval: false,
    requiresResolutionCheck: false,
    terminal: false,
    enabled: true,
    version: 'v1'
  },

  CHANGE_PAYMENT_METHOD_PROMPT: {
    type: 'CHANGE_PAYMENT_METHOD_PROMPT',
    name: 'Prompt Change Payment Method',
    description: 'Display in-app or checkout modal prompting customer to switch payment instrument',
    supportedCauses: [
      'INSUFFICIENT_FUNDS',
      'CREDIT_LIMIT_EXCEEDED',
      'MANUAL_3DS_OTP_ABANDONMENT',
      '3DS_OTP_ABANDONMENT',
      'ACQUIRER_PAYMENT_GATEWAY_TIMEOUT',
      'GATEWAY_TIMEOUT',
      'ISSUING_BANK_OUTAGE',
      'ISSUER_TECHNICAL_FAILURE',
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE',
      'PAYMENT_INSTRUMENT_EXPIRED_INVALID',
      'PAYMENT_INSTRUMENT_INVALID',
      'EXPIRED_CARD',
      'INVALID_CARD',
      'INVALID_CVV',
      'TRANSACTION_LIMIT_EXCEEDED'
    ],
    priority: 'HIGH',
    estimatedCost: 0,
    expectedRecoveryProbability: 0.75,
    maxAttempts: 3,
    cooldownSeconds: 0,
    requiredCustomerData: ['customerIdentity'],
    requiredMerchantConfig: [],
    supportedChannels: ['SDK_IN_APP'],
    requiresPaymentLink: false,
    requiresHumanApproval: false,
    requiresResolutionCheck: false,
    terminal: false,
    enabled: true,
    version: 'v1'
  },

  SEND_EMAIL: {
    type: 'SEND_EMAIL',
    name: 'Send Email Notification',
    description: 'Dispatch transactional recovery email to customer',
    supportedCauses: [
      'INSUFFICIENT_FUNDS',
      'CREDIT_LIMIT_EXCEEDED',
      'MANUAL_3DS_OTP_ABANDONMENT',
      '3DS_OTP_ABANDONMENT',
      'ACQUIRER_PAYMENT_GATEWAY_TIMEOUT',
      'GATEWAY_TIMEOUT',
      'ISSUING_BANK_OUTAGE',
      'ISSUER_TECHNICAL_FAILURE',
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE',
      'PAYMENT_INSTRUMENT_EXPIRED_INVALID',
      'PAYMENT_INSTRUMENT_INVALID',
      'EXPIRED_CARD',
      'INVALID_CARD',
      'INVALID_CVV',
      'TRANSACTION_LIMIT_EXCEEDED'
    ],
    priority: 'MEDIUM',
    estimatedCost: 0.1,
    expectedRecoveryProbability: 0.40,
    maxAttempts: 3,
    cooldownSeconds: 3600,
    requiredCustomerData: ['email'],
    requiredMerchantConfig: ['emailEnabled'],
    supportedChannels: ['EMAIL'],
    requiresPaymentLink: true,
    requiresHumanApproval: false,
    requiresResolutionCheck: false,
    terminal: false,
    enabled: true,
    version: 'v1'
  },

  SEND_SMS: {
    type: 'SEND_SMS',
    name: 'Send SMS Notification',
    description: 'Dispatch SMS text message with recovery details to customer phone',
    supportedCauses: [
      'INSUFFICIENT_FUNDS',
      'CREDIT_LIMIT_EXCEEDED',
      'MANUAL_3DS_OTP_ABANDONMENT',
      '3DS_OTP_ABANDONMENT',
      'ACQUIRER_PAYMENT_GATEWAY_TIMEOUT',
      'GATEWAY_TIMEOUT',
      'ISSUING_BANK_OUTAGE',
      'ISSUER_TECHNICAL_FAILURE',
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE',
      'PAYMENT_INSTRUMENT_EXPIRED_INVALID',
      'PAYMENT_INSTRUMENT_INVALID',
      'EXPIRED_CARD',
      'INVALID_CARD',
      'INVALID_CVV',
      'TRANSACTION_LIMIT_EXCEEDED'
    ],
    priority: 'MEDIUM',
    estimatedCost: 0.25,
    expectedRecoveryProbability: 0.50,
    maxAttempts: 2,
    cooldownSeconds: 1800,
    requiredCustomerData: ['phone'],
    requiredMerchantConfig: ['smsEnabled'],
    supportedChannels: ['SMS'],
    requiresPaymentLink: true,
    requiresHumanApproval: false,
    requiresResolutionCheck: false,
    terminal: false,
    enabled: true,
    version: 'v1'
  },

  SEND_WHATSAPP: {
    type: 'SEND_WHATSAPP',
    name: 'Send WhatsApp Notification',
    description: 'Dispatch WhatsApp message with interactive payment link to customer',
    supportedCauses: [
      'INSUFFICIENT_FUNDS',
      'CREDIT_LIMIT_EXCEEDED',
      'MANUAL_3DS_OTP_ABANDONMENT',
      '3DS_OTP_ABANDONMENT',
      'ACQUIRER_PAYMENT_GATEWAY_TIMEOUT',
      'GATEWAY_TIMEOUT',
      'ISSUING_BANK_OUTAGE',
      'ISSUER_TECHNICAL_FAILURE',
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE',
      'PAYMENT_INSTRUMENT_EXPIRED_INVALID',
      'PAYMENT_INSTRUMENT_INVALID',
      'EXPIRED_CARD',
      'INVALID_CARD',
      'INVALID_CVV',
      'TRANSACTION_LIMIT_EXCEEDED'
    ],
    priority: 'MEDIUM',
    estimatedCost: 0.4,
    expectedRecoveryProbability: 0.65,
    maxAttempts: 2,
    cooldownSeconds: 1800,
    requiredCustomerData: ['phone'],
    requiredMerchantConfig: ['whatsappEnabled'],
    supportedChannels: ['WHATSAPP'],
    requiresPaymentLink: true,
    requiresHumanApproval: false,
    requiresResolutionCheck: false,
    terminal: false,
    enabled: true,
    version: 'v1'
  },

  HUMAN_REVIEW: {
    type: 'HUMAN_REVIEW',
    name: 'Escalate to Human Review',
    description: 'Flag complex/high-value failure for merchant support team manual intervention',
    supportedCauses: [
      'TECHNICAL_FAILURE',
      'MERCHANT_TECHNICAL_FAILURE',
      'TRANSACTION_LIMIT_EXCEEDED'
    ],
    priority: 'HIGH',
    estimatedCost: 10.0,
    expectedRecoveryProbability: 0.85,
    maxAttempts: 1,
    cooldownSeconds: 86400,
    requiredCustomerData: [],
    requiredMerchantConfig: ['humanReviewEnabled', 'humanReviewContact'],
    supportedChannels: ['DASHBOARD', 'EMAIL_ALERT'],
    requiresPaymentLink: false,
    requiresHumanApproval: true,
    requiresResolutionCheck: false,
    terminal: true,
    enabled: true,
    version: 'v1'
  }
};
